import numpy as np


class ReversiEnv:

    def __init__(self):
        ...

    def step(self, action):
        state = ...
        reward = ...
        done = ...
        return state, reward, done, {}

    def reset(self):
        state = ...
        return state

    def render(self, mode='human', close=False):
        ...

    def close(self):
        ...
